---
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2015
      end: 'latest'
